repository:
  name: web-mdm-dashboard
  description: New generation of the Flyve MDM Dashboard 
  homepage: http://flyve.org/web-mdm-dashboard/
  topics: flyve-mdm, dashboard, admin, web, glpi
  private: false
  has_issues: true
  has_wiki: false
  has_downloads: true
  default_branch: develop
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
labels:
  - name: api
    color: 0052cc
  - name: bug
    color: f44336
  - name: build
    color: 795548
  - name: ci
    color: fbca04
  - name: documentation
    color: 607d8b
  - name: duplicate
    color: 9e9e9e
  - name: enrollment
    color: 5319e7
  - name: feature
    color: 3f51b5
  - name: good first issue
    color: 7057ff
  - name: greenkeeper
    color: 00c775
  - name: hacktoberfest
    color: ff625f
  - name: help wanted
    color: 33aa3f
  - name: install
    color: ffa31a
  - name: invalid
    color: cddc39
  - name: inventory
    color: 40bf80
  - name: locales
    color: d4c5f9
  - name: notification
    color: cc6699
  - name: performance
    color: 009688
  - name: policy
    color: 7575f0
  - name: question
    color: ff5722
  - name: refactor
    color: 9c27b0
  - name: style
    color: 2196f3
  - name: test
    color: 8bc34a
  - name: transversal development
    color: b60205
  - name: ui
    color: bfdadc
  - name: user
    color: 0066cc
  - name: wontfix
    color: ffffff
