before_script:
  - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update && sudo apt-get install yarn
  - npm rebuild node-sass
  - yarn install

stages:
  - deploy

deployment:
  stage: deploy
  script:
    - yarn build
    - source ci/scripts/copy_build.sh
  only:
    - develop
    