version: 2

references:
  # Configuration
  workspace: &workspace  ~/flyve

  docker_image: &docker_image node:8.11

  container_config: &container_config
    docker:
      - image: *docker_image
    working_directory: *workspace

  transifex_config: &transifex_config
    run:
      name: Configure transifex
      command: source ci/scripts/transifex_config.sh

  transifex_sync: &transifex_sync
    run:
      name: Synchronize translations to transifex
      command: source ci/scripts/transifex_sync.sh

  # Dependencies
  system_install: &system_install
    run:
      name: Update system dependencies
      command: source ci/scripts/system_install.sh

  node_install: &node_install
    run:
      name: Install node dependencies
      command: source ci/scripts/node_install.sh

  python_install: &python_install
    run:
      name: Install python dependencies
      command: source ci/scripts/python_install.sh

  # Build application
  build_app: &build_app
    run:
      name: "Build application"
      command: |
        source ci/scripts/create_config_file.sh
        yarn build

  # Test configuration
  start_server: &start_server
    run:
      name: Start server in background
      command: yarn start:only > ../yarn.log
      background: true

  unit_test: &unit_test
    run:
      name: Run unit tests
      command: yarn test

  end_to_end_test: &end_to_end_test
    run:
      name: Run End-to-End tests
      command: |
        until grep -m 1 'Compiled successfully!' ../yarn.log ; do true; done
        yarn test:cypress

  webhint_test: &webhint_test
    run:
      name: Run webhint tests
      command: |
        until grep -m 1 'Compiled successfully!' ../yarn.log ; do true; done
        yarn test:webhint

  validate_html: &validate_html
    run:
      name: Validate HTML
      command: html5validator --root build/

  # Settings deploy
  git_config: &git_config
    run:
      name: Configure GIT
      command: source ci/scripts/git_config.sh

  deploy_app: &deploy_app
    run:
      name: Deploy application
      command: source ci/scripts/deploy.sh

  create_release: &create_release
    run:
      name: Generate release
      command: source ci/scripts/release.sh

  create_screenshots: &create_screenshots
    run:
      name: Generate screenshots
      command: source ci/scripts/screenshots.sh

  create_documentation: &create_documentation
    run:
      name: Generate documentation
      command: source ci/scripts/documentation.sh
      environment:
        DOCUMENTATION_DESTINATION: development/coverage/{{ .Environment.CIRCLE_BRANCH }}

  create_coverage: &create_coverage
    run:
      name: Generate coverage
      command: source ci/scripts/coverage.sh
      environment:
        COVERAGE_DESTINATION: development/code-documentation/{{ .Environment.CIRCLE_BRANCH }}

  release_master: &release_master
    run:
      name: Release master branch
      command: source ci/scripts/release_master.sh

  zip_build: &zip_build
    run:
      name: Pack build folder
      command: zip -r ./build.zip build/*

  # Handle cache
  node_key: &node_key yarn-dependencies-v1-{{ checksum "yarn.lock" }}

  build_key: &build_key build-app-v1-{{ .Environment.CIRCLE_WORKFLOW_ID }}

  screenshots_key: &screenshots_key screenshots-app-v1-{{ .Environment.CIRCLE_WORKFLOW_ID }}

  store_node_cache: &store_node_cache
    save_cache:
      key: *node_key
      paths:
        - node_modules
        - /root/.cache/Cypress

  store_build_cache: &store_build_cache
    save_cache:
      key: *build_key
      paths:
        - build
        - public/config.js
        # - reports

  store_screenshots: &store_screenshots
    save_cache:
      key: *screenshots_key
      paths:
        - cypress/screenshots

  restore_node_cache: &restore_node_cache
    restore_cache:
      key: *node_key

  restore_build_cache: &restore_build_cache
    restore_cache:
      key: *build_key

  restore_screenshots_cache: &restore_screenshots_cache
    restore_cache:
      key: *screenshots_key

  # Handle artifact
  build_artifact: &build_artifact
    run:
      name: Create build artifact
      command: |
        mkdir /tmp/artifacts
        zip -r ./build.zip build/* > /tmp/artifacts/build.zip

  store_build_artifact: &store_build_artifact
    store_artifacts:
      path: /tmp/artifacts
      destination: artifacts

jobs:
  build:
    <<: *container_config

    steps:
      - checkout
      - *system_install
      - *python_install
      - *restore_node_cache
      - *node_install
      - *store_node_cache
      - *transifex_config
      - *transifex_sync
      - *build_app
      - *store_build_cache

  test:
    <<: *container_config

    steps:
      - checkout
      - *system_install
      - *python_install
      - *restore_node_cache
      - *restore_build_cache
      - *start_server
      - *unit_test
      - *end_to_end_test
      - *webhint_test
      - *restore_build_cache
      - *validate_html
      - *store_screenshots

  screenshots:
    <<: *container_config

    steps:
      - checkout
      - *system_install
      - *restore_node_cache
      - *git_config
      - *restore_screenshots_cache
      - *create_screenshots

  documentation:
    <<: *container_config

    steps:
      - checkout
      - *system_install
      - *restore_node_cache
      - *git_config
      - *create_documentation

  coverage:
    <<: *container_config

    steps:
      - checkout
      - *system_install
      - *restore_node_cache
      - *git_config
      # - *restore_build_cache
      - *create_coverage

  release:
    <<: *container_config

    steps:
      - checkout
      - *system_install
      - *restore_node_cache
      - *git_config
      - *restore_build_cache
      - *zip_build
      - *create_release

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - screenshots:
          requires:
            - test
          filters:
            branches:
              only:
                - master
      - documentation:
          requires:
            - test
          filters:
            branches:
              only:
                - master
                - develop
      - coverage:
          requires:
            - test
          filters:
            branches:
              only:
                - master
                - develop
      - release:
          requires:
            - screenshots
            - documentation
            - coverage
          filters:
            branches:
              only:
                - master
